baseURL = 'https://ThornDuke.github.io/'
languageCode = 'it'
title = 'Hacker Nirvana'
theme = "ananke"
resourceDir = "../resources"

 DefaultContentLanguage = "it"
 SectionPagesMenu = "main"
 Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
 enableRobotsTXT = true

[languages]
  [languages.it]
    title = "Sam Sahara"
    weight = 1
    contentDir = "content/it"

#[sitemap]
#  changefreq = "monthly"
#  priority = 0.5
#  filename = "sitemap.xml"

[params]
  author = "Sergio Spina"
  description = "Il blog di Sam Sahara"
#  disqusShortname = "hacker-nirvana"
#  favicon = ""
#  site_logo = ""
#  facebook = ""
#  twitter = ""
#  instagram = ""
#  youtube = ""
#  github = ""
#  gitlab = ""
#  linkedin = ""
#  mastodon = ""
#  slack = ""
#  stackoverflow = ""
#  rss = ""
#  # choose a background color from any on this page:
#  # http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
#  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#  recent_posts_number = 2

